### ISSUE TITLE
Please publish latest version of a3700_utils

### ISSUE THREAD

**Issue by pali** [MarvellEmbeddedProcessors/A3700-utils-marvell#13]
Marvell SDK-10.3.5.0-PR1 contains new version of a3700_utils with new patches which are not available in the publically latest branch A3700_utils-armada-18.12-fixed.

Please publish latest version of a3700_utils from Marvell SDK which is currently available only under NDA.

**Comment by pali** [comment]
@kostapr: Could you please look at this issue?

**Comment by kostapr** [comment]
@pali, let me check if I can legally do it.

**Comment by pali** [comment]
@kostapr: Thanks! Have you find some way how to publish it?

**Comment by kostapr** [comment]
@pali I just got a green light from my manager. Will push updates shortly

**Comment by kostapr** [comment]
@pali, please check the new branch. I did not want to destroy the current default one. If it works well, we can make it default. 
https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell/tree/A3700_utils-armada-3.0.0-fixed

**Comment by pali** [comment]
Thank you! I will look at them.

CC @heaterC: You could be interested in [new](https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell/tree/A3700_utils-armada-3.0.0-fixed) A3700-utils-marvell version too!

**Comment by heaterC** [comment]
Built an image from [this branch](https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell/tree/A3700_utils-armada-3.0.0-fixed) but it does not run on my EspressoBin DDR4 1GB 1cs: Board switches to backup U-Boot.

**Comment by pali** [comment]
Seems that in commit 8cb7fbe9f22ce9a893f5dbecad8734d4e23b5e1a from A3700_utils-armada-3.0.0-fixed branch is a bug. twin-die combined chip has value `1` and single die(regular) is default and has value `0`. Could you therefore try to switch ddr_twin_die_index=1 to ddr_twin_die_index=0 in DDR_TOPOLOGY*.txt files? This looks like a same problem as which we have fixed in https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/pull/25 for mv-ddr-marvell repository (as you know without fixing twin-die enum booting have not worked).

**Comment by heaterC** [comment]
That was it. It's booting now on my device.

**Comment by pali** [comment]
@kostapr: Would you fix this mentioned issue in A3700_utils-armada-3.0.0-fixed branch?

**Comment by kostapr** [comment]
@pali & @heaterC , our private DDR code still has the twin die enum defined as following:
enum mv_ddr_twin_die {
        COMBINED,
        NOT_COMBINED,
};
If I fix this this mismatch in A3700 utils here and then get approval of sharing the latest mv_ddr code on Github, it will require additional fix. Maybe it will be better to revert the patch [56db5d1464b44df10a02b99e615ebd6f6a35c428 ](https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/commit/56db5d1464b44df10a02b99e615ebd6f6a35c428)?

**Comment by pali** [comment]
Reverting https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/commit/56db5d1464b44df10a02b99e615ebd6f6a35c428 commit will lead to unbootable of all A3720 devices when they will use any other version of A3700_utils in this repository and also in other repository forks.

**Comment by kostapr** [comment]
I see. I pushed the [fix](https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell/commit/5598e150fa3a1568256c30223fd2b214d729f26a)

**Comment by pali** [comment]
Thank you!

**Comment by pali** [comment]
@kostapr: Could you create "master" branch which would point to the latest code, so now to the "A3700_utils-armada-3.0.0-fixed" branch?

Because now everytime when new version was released it was required to update steps for building ARM trusted firmeare which complicates things for all projects which are building firmwares for Espressobin and other boards.

If there is classic "master" branch which contains up-to-date code it is not needed to always update instructions how to build ARM trusted firmware and therefore it can simplify whole build setup.

You can still use separate branches like before, just to introduce new master branch which would point to the lastest up-to-date code.

**Comment by kostapr** [comment]
@pali, done. The master branch is now aligned with A3700_utils-armada-3.0.0-fixed

**Comment by pali** [comment]
Perfect, thank you very much! Can you also set `master` branch to be repository default branch (and therefore it does not have to be needed to change it again in the furure)?

**Comment by kostapr** [comment]
I need to ask the project administrator (@haklai) to do so. I do not have permission to change the default project branch.

**Comment by pali** [comment]
@kostapr: I have tested current master branch too and it is working fine for me too!

I have there some changes for A3700-utils-marvell. Should I open a pull request for `master` branch?

**Comment by kostapr** [comment]
Hi, @pali, yes, please.

**Comment by pali** [comment]
@kostapr: Could you try to ask for switching base github branch to `master` where is currently the latest codebase?

**Comment by kostapr** [comment]
@haklai, could you please set the master branch as a default one?

**Comment by pali** [comment]
I see that default branch for A3700-utils-marvell is now `master`, thank you very much!

Can you do it also for https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell repository?

**Comment by kostapr** [comment]
@pali I think we already did this in the past. For this kind of requests you need to ping @haklai since he has the administrator rights on Marvell Github projects

**Comment by pali** [comment]
Default branch for `A3700-utils-marvell` repository is `master` as can be seen on page:
https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell/branches

But default branch for `mv-ddr-marvell` is _not_ `master`, so it is not updated, as can be seen on:
https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/branches

@haklai: Could you update default branch also for `mv-ddr-marvell` to master?

**Comment by pali** [comment]
Now both repositories have `master` branch as default, thank you very much!
