### ISSUE TITLE
ddr3_tool binary issues

### ISSUE THREAD

**Issue by afaerber** [MarvellEmbeddedProcessors/A3700-utils-marvell#2]
Branch A3700_utils-armada-17.10 contains `ddr/tim_ddr/ddr3_tool` and `ddr/tim_ddr/ddr4_tool` binaries without source code or license information. These tools are called by `ddr/tim_ddr/ddrparser.pl`, and it unlinks the `ddr/tim_ddr/ddr_static.txt` output file before calling the tools, so that it cannot easily be supplied pre-generated.

a) Please add licensing information indicating that the files are redistributable.

b) Is there any chance you can add the source code for these tools, as done for TBB_linux, so that they can be rebuilt for, e.g., aarch64?

Currently I've needed to patch ddrparser.pl, commenting out the unlink and ddr3_tool parts.

**Comment by netazurh** [comment]
Regarding the ddr tool , I'll push a new branch 18.06 in the next days with the ddr tool code.
a. I added BSD license 
b. the code is already there

**Comment by afaerber** [comment]
Thanks, looking forward to it!
Please check your author email address though. :)
